on: [push]
name: customBlockManager
jobs:
  customBlockManager:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ojs
            php-version: 8.3
            database: mysql
          - application: ojs
            php-version: 8.2
            database: mysql
          - application: ojs
            php-version: 8.3
            database: pgsql
          - application: ojs
            php-version: 8.2
            database: pgsql


    name: customBlockManager
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
         node_version: 20
         branch: main
         repository: pkp
         plugin: true

      - name: Setup tmate session by failure
        if: ${{ failure()}}
        uses: mxschmitt/action-tmate@v3

